### ISSUE TITLE
Investigate failing tests

### ISSUE THREAD

**Issue by floere** [CocoaPods/metrics.cocoapods.org#24]

**Comment by k0nserv** [comment]
Here's the output I get

```
--------------------------------------------------------------------------------
[0;36mRunning the specs[0m
--------------------------------------------------------------------------------


Metrics::Github
  with a dot in the repository name
[32m    ✓ [0mhas the right user
[32m    ✓ [0mhas the right repo
  with a .git github URL
[32m    ✓ [0mhas the right user
[32m    ✓ [0mhas the right repo
  with a non .git github URL
[32m    ✓ [0mhas the right user
[32m    ✓ [0mhas the right repo
  with a private github URL
[32m    ✓ [0mhas the right user
[32m    ✓ [0mhas the right repo
  with a ? github URL
[32m    ✓ [0mhas the right user
[32m    ✓ [0mhas the right repo
  with an error case
[32m    ✓ [0mhas the right user
[32m    ✓ [0mhas the right repo
  not_found
[32m    ✓ [0mupdates not found on existing github metrics (9 ms)
[32m    ✓ [0mcreates metrics with not found (4 ms)
  reset_not_found
[32m    ✓ [0mresets not found on existing github metrics (5 ms)
[32m    ✓ [0mignores metrics with no not found
  .update
[32m    ✓ [0mraises RateLimitError when rate limiting is in effect (49 ms)
[32m    ✓ [0mupdates correctly (104 ms)

MetricsApp /api/v1/status
[32m  ✓ [0mreturns the right amount (43 ms)

Metrics::Updater
  find_pods_without_github_pod_metrics
    pods without metrics
[32m      ✓ [0mfinds them (3 ms)
  find_pods_with_old_github_pod_metrics
    pods without metrics
[32m      ✓ [0mfinds them (4 ms)
    pods with old and low not_found metrics
[32m      ✓ [0mfinds them (3 ms)
    pods with old and high not_found metrics
[32m      ✓ [0mfinds them (3 ms)
  .reset
[32m    ✓ [0mresets not found on existing github metrics (5 ms)
[32m    ✓ [0mignores metrics with no not found (2 ms)

Pod
  #specification_json
[31m    - returns the data of the last version [FAILED][0m
  .with_github_pod_metrics
[32m    ✓ [0mreturns a combined model (5 ms)
  .oldest
[32m    ✓ [0mreturns the least recently updated X pods (4 ms)
  .without_github_pod_metrics
    with some github metrics
[32m      ✓ [0mreturns the pods without github metrics (4 ms)
    without github metrics
[32m      ✓ [0mreturns the least recently updated X pods (3 ms)
  .with_old_github_pod_metrics
    with updated_at
[32m      ✓ [0mreturns the least recently updated X pods (5 ms)
    without updated_at
[32m      ✓ [0mreturns the least recently updated X pods (5 ms)
  #github_url
    Non-.git extension
[32m      ✓ [0mextracts the github_url correctly (2 ms)

MetricsApp when receiving hook calls from trunk
[32m  ✓ [0msucceeds without a pod (5 ms)
[32m  ✓ [0mresets metrics with a pod (3 ms)
[32m  ✓ [0mredirects root to status (3 ms)

MetricsApp /api/v1/pods/:name
[31m  - returns the right details [FAILED][0m
[31m  - returns the right details [FAILED][0m

Sequel::ForeignKeyConstraintViolation: PG::ForeignKeyViolation: ERROR:  insert or update on table "commits" violates foreign key constraint "commits_committer_id_fkey"
DETAIL:  Key (committer_id)=(1) is not present in table "owners".

[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/adapters/postgres.rb:161:in `async_exec': #specification_json - returns the data of the last version
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/adapters/postgres.rb:161:in `block in execute_query'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/logging.rb:37:in `log_yield'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/adapters/postgres.rb:161:in `execute_query'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/adapters/postgres.rb:148:in `block in execute'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/adapters/postgres.rb:124:in `check_disconnect_errors'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/adapters/postgres.rb:148:in `execute'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/adapters/postgres.rb:483:in `_execute'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/adapters/postgres.rb:307:in `block (2 levels) in execute'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/adapters/postgres.rb:504:in `check_database_errors'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/adapters/postgres.rb:307:in `block in execute'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/connecting.rb:229:in `block in synchronize'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/connecting.rb:229:in `synchronize'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/adapters/postgres.rb:307:in `execute'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/dataset/actions.rb:900:in `execute'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/adapters/postgres.rb:627:in `fetch_rows'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/dataset/actions.rb:1004:in `returning_fetch_rows'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/dataset/actions.rb:333:in `insert'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/adapters/shared/postgres.rb:1248:in `insert'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/adapters/shared/postgres.rb:1264:in `insert_select'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1791:in `_insert_select_raw'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1764:in `_insert'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1828:in `block (2 levels) in _save'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1107:in `around_create'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1825:in `block in _save'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1107:in `around_save'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1820:in `_save'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1520:in `block (2 levels) in save'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1978:in `block in checked_transaction'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/transactions.rb:97:in `block in transaction'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/connecting.rb:229:in `block in synchronize'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/connecting.rb:229:in `synchronize'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/transactions.rb:89:in `transaction'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1978:in `checked_transaction'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1520:in `block in save'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1966:in `checked_save_failure'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1520:in `save'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/associations.rb:1975:in `block in def_one_to_many'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/associations.rb:2135:in `add_associated_object'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/associations.rb:1747:in `block in def_association_instance_methods'
[0m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/unit/models/pod_spec.rb:11:in `block (3 levels) in <top (required)>'
[0m[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:37:in `block in run_requirement'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/transactions.rb:119:in `_transaction'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/transactions.rb:100:in `block in transaction'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/connecting.rb:229:in `block in synchronize'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/connecting.rb:229:in `synchronize'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/transactions.rb:89:in `transaction'
[0m[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:36:in `run_requirement'
[0m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/unit/models/pod_spec.rb:15:in `block (2 levels) in <top (required)>'
[0m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/unit/models/pod_spec.rb:7:in `block in <top (required)>'
[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:60:in `instance_eval'
[0m[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:60:in `block in describe'
[0m[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:57:in `describe'
[0m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/unit/models/pod_spec.rb:5:in `<top (required)>'

Sequel::Error: method not_found= doesn't exist
[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:2045:in `block in set_restricted': MetricsApp /api/v1/pods/:name - returns the right details
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:2032:in `each'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:2032:in `set_restricted'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1544:in `set'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1997:in `initialize_set'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1146:in `initialize'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:148:in `new'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:148:in `create'
[0m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/functional/api/v1/pods_spec.rb:22:in `block (2 levels) in <top (required)>'
[0m[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:37:in `block in run_requirement'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/transactions.rb:119:in `_transaction'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/transactions.rb:100:in `block in transaction'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/connecting.rb:229:in `block in synchronize'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/connecting.rb:229:in `synchronize'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/transactions.rb:89:in `transaction'
[0m[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:36:in `run_requirement'
[0m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/functional/api/v1/pods_spec.rb:41:in `block in <top (required)>'
[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:60:in `instance_eval'
[0m[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:60:in `block in describe'
[0m[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:57:in `describe'
[0m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/functional/api/v1/pods_spec.rb:5:in `<top (required)>'

Sequel::Error: method not_found= doesn't exist
[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:2045:in `block in set_restricted': MetricsApp /api/v1/pods/:name - returns the right details
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:2032:in `each'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:2032:in `set_restricted'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1544:in `set'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1997:in `initialize_set'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:1146:in `initialize'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:148:in `new'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/model/base.rb:148:in `create'
[0m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/functional/api/v1/pods_spec.rb:22:in `block (2 levels) in <top (required)>'
[0m[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:37:in `block in run_requirement'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/transactions.rb:119:in `_transaction'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/transactions.rb:100:in `block in transaction'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/connecting.rb:229:in `block in synchronize'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/connecting.rb:229:in `synchronize'
[0m[0;37m	/Users/hugotunius/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/sequel-4.10.0/lib/sequel/database/transactions.rb:89:in `transaction'
[0m[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:36:in `run_requirement'
[0m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/functional/api/v1/pods_spec.rb:75:in `block in <top (required)>'
[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:60:in `instance_eval'
[0m[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:60:in `block in describe'
[0m[0;37m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/spec_helper.rb:57:in `describe'
[0m	/Users/hugotunius/Development/iOS/CocoaPods-main/metrics.cocoapods.org/spec/functional/api/v1/pods_spec.rb:5:in `<top (required)>'

[31m38 specifications (51 requirements), 0 failures, 3 errors[0m
```
